version: "3.9"

services:
  app:
    build:
      container_name: spring-docker
      port:
        - "8564:8080"
      network:
        - "spring-net"

nginx:
  image: nginx:latest
  container_name: spring-nginx
  port:
    - "8564:8080"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  depend_on:
    - app
  networks:
    - spring-net

networks:
  spring-net:
    driver: bridge
